# Generated by Django 5.0.4 on 2024-04-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Nome de Perfil')),
                ('profile_bio', models.TextField(blank=True, max_length=255, null=True, verbose_name='Biografia do Perfil')),
                ('profile_photo', models.ImageField(upload_to='perfil_photos/', verbose_name='Foto de Perfil')),
                ('profile_background', models.ImageField(upload_to='profile_backgrounds/', verbose_name='Fundo do Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
