# Generated by Django 5.0.4 on 2024-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(null=True, upload_to='profile_backgrounds/', verbose_name='Fundo do Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='perfil_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
