# Generated by Django 5.0.4 on 2024-07-10 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/', verbose_name='Fundo do Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SP', 'Spam'), ('OC', 'Conteúdo Ofensivo'), ('HB', 'Assédio ou Bullying'), ('IM', 'Impersonação'), ('IC', 'Conteúdo Inapropriado'), ('MI', 'Informações Falsas'), ('CV', 'Violação de Direitos Autorais'), ('SY', 'Segurança e Privacidade'), ('IA', 'Conduta Ilegal'), ('HS', 'Discurso de Ódio e Discriminação'), ('CA', 'Abuso Infantil'), ('OT', 'Outros')], default='OT', max_length=2)),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descrição do report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
